### ISSUE TITLE
command line options for bigip 

### ISSUE THREAD

**Issue by dflanigan** [F5Networks/f5-openstack-test#18]
py.test BigIP command line options defined f5_os_test/infrastruction.py should have "bigip" in them.
If the option specifies an address, that should be in the option too.  Use - and not _ .

--bigip should be --bigip-address

--username should be --bigip-username

--password should be --bigip-password

--auth_address should be --auth-address

**Comment by zancas** [comment]
@pjbreaux I agree with @dflanigan .

**Comment by pjbreaux** [comment]
No longer valid now that we are using symbols.
